server:
  port: 8841
spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #default 8719, if not +1 +1...
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-servce
            data-type： json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: "*"
