server:
  port: 8841
spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #default 8719, if not +1 +1...
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
