server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false
    username: root
    password: root

feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info
#
#mybatis:
#  mapperLocationsL classpath:mapper/*.xml
